### ISSUE TITLE
反向回显效果有问题

### ISSUE THREAD

**Issue by xingorg1** [willxiao90/cron-picker-vue#2]
![](https://cdn.jsdelivr.net/gh/xingorg1/xingorg1Blog/2021-7-29/1627541866818-image.png)

**Comment by willxiao90** [comment]
这是个 bug，反向回显的问题比较多，因为用户输入的内容是无法预测的，也有可能是非法的，所以自 v1.0.10 版本之后，去掉了反向回显功能。UI 也改成了 popover 弹窗的形式，具体请看最新 [Demo](https://willxiao90.github.io/cron-picker-vue/)
