### ISSUE TITLE
使用示例的代码，<cron-picker>组件中的各种组件都挤在了一起

### ISSUE THREAD

**Issue by xuhaojie66** [willxiao90/cron-picker-vue#3]
使用示例的代码，cron-picker组件中的各种组件都挤在了一起，如何设置成像demo显示的那样，组件上下之间留有一定间隙

**Comment by willxiao90** [comment]
需要使用 import "cron-picker-vue/dist/CronPicker.css" 引入组件的 css 样式文件的（readme 已经更新了）
